"""Clean the raw Kaggle reviews file and write data/clean/reviews.parquet + DATA_QUALITY.md."""
import pandas as pd

RAW = "data/raw/Womens Clothing E-Commerce Reviews.csv"
raw = pd.read_csv(RAW, index_col=0)
log = [("Raw rows", len(raw), "Starting point")]

d = raw.rename(columns={"Clothing ID": "clothing_id", "Age": "age", "Title": "title", "Review Text": "text",
                        "Rating": "rating", "Recommended IND": "recommended", "Positive Feedback Count": "helpful_votes",
                        "Division Name": "division", "Department Name": "department", "Class Name": "class_name"})
d.index.name = "review_id"  # original row number, kept so every label traces back to the raw file

d["text"] = d["text"].str.strip()
blank = d["text"].isna() | (d["text"] == "")
log.append(("Reviews with no text", int(blank.sum()), "Dropped: nothing to classify"))
d = d[~blank]

dup = d["text"].duplicated()
log.append(("Exact duplicate review text", int(dup.sum()), "Dropped, first copy kept"))
d = d[~dup]

short = d["text"].str.len() < 20
log.append(("Reviews under 20 characters", int(short.sum()), "Kept: still carry a rating and a short opinion"))

no_dept = d["department"].isna()
log.append(("Missing department/division/class", int(no_dept.sum()), "Kept, labelled 'Unknown'"))
d[["division", "department", "class_name"]] = d[["division", "department", "class_name"]].fillna("Unknown")

log.append(("Title missing", int(d["title"].isna().sum()), "Kept: title is not used for classification"))
bad_rating = ~d["rating"].between(1, 5)
log.append(("Rating outside 1-5", int(bad_rating.sum()), "None expected; dropped if any"))
d = d[~bad_rating]
log.append(("Final rows", len(d), "Population the 1,500-review sample is drawn from"))

d.to_parquet("data/clean/reviews.parquet")
with open("DATA_QUALITY.md", "w", encoding="utf-8") as f:
    f.write("# Data quality log\n\nGenerated by `clean.py`. Counts are computed, not typed.\n\n"
            "| Check | Rows | Decision |\n|---|---|---|\n")
    f.writelines(f"| {c} | {n:,} | {why} |\n" for c, n, why in log)
print(f"raw {len(raw)} -> clean {len(d)}")
